### ISSUE TITLE
anyone can provide python implementations?

### ISSUE THREAD

**Issue by EsqerYasen** [antirez/smallchat#25]
I watched the video mentioned in the repo. I want to know his specific principles and philosophy of the code. Can anyone provide a python implementation of the code?

**Comment by qycyfjy** [comment]
Main idea of it is to use `select` to monitor multiple sockets. It looks a bit verbose because of C.

I wrote a similar one when I was looking at the python [selectors](https://docs.python.org/3/library/selectors.html#module-selectors) library before. Now I modified it a little and uploaded it to my github. If you are interested, you can take a look.
[here](https://github.com/qycyfjy/py-chat/tree/master)

**Comment by EsqerYasen** [comment]
> Main idea of it is to use `select` to monitor multiple sockets. It looks a bit verbose because of C.
> 
> I wrote a similar one when I was looking at the python [selectors](https://docs.python.org/3/library/selectors.html#module-selectors) library before. Now I modified it a little and uploaded it to my github. If you are interested, you can take a look. [here](https://github.com/qycyfjy/py-chat/tree/master)

@qycyfjy  thanks, this is helpful.
